Importing Numpy

In [2]:
import numpy as np

Checking numpy version and configuration

In [ ]:
print(np.__version__)
np.show_config()

Creating null vector of size 10

In [3]:
n = np.zeros(10)
print(n)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null vector of size 10 but the fifth value which is 1

In [5]:
n = np.zeros(10)
n[4] = 1
print(n)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [6]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


Reverse a vector (first element becomes last)

In [11]:
r = np.arange(20)
print("Original: ",r)
r= r[::-1]
print('Reverse: ',r)

Original:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Reverse:  [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


9. Find indices of non­zero elements from [1,2,0,0,4,0]

In [13]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


10. Create a 3x3 identity matrix

In [14]:
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create a 3x3x3 array with random values

In [17]:
ra = np.random.random((3,3,3))
print(ra)

[[[0.21372228 0.66623143 0.4672544 ]
  [0.70026123 0.60767743 0.8249298 ]
  [0.4604358  0.38536196 0.64892549]]

 [[0.97432697 0.00633154 0.0622781 ]
  [0.05162091 0.47922388 0.29882478]
  [0.63167643 0.92035249 0.16149025]]

 [[0.86124725 0.83727132 0.06612609]
  [0.11005147 0.14708561 0.11010491]
  [0.4472167  0.5636747  0.72306408]]]


12. Create a 10x10 array with random values and find the minimum and maximum
values

In [21]:
x = np.random.random((10,10))
print(x)
print()
print("Minimum value",x.min())
print("Maximum value",x.max())

[[6.39666200e-01 9.75397020e-01 2.32572150e-01 2.89163267e-01
  7.62611574e-01 9.22998688e-01 6.33380059e-01 6.71125227e-01
  2.47996360e-01 9.03934345e-01]
 [1.68002073e-01 4.26364925e-01 2.34358943e-01 4.43140507e-01
  1.10539078e-01 1.12327448e-01 8.44603479e-01 1.69061519e-01
  5.96986288e-01 4.60809381e-02]
 [9.33077770e-02 8.29867858e-01 8.98705646e-02 9.99457291e-01
  4.11488053e-02 3.24964516e-01 6.47299751e-01 2.98562605e-01
  4.68942128e-01 5.03595766e-01]
 [5.81024217e-01 2.66485013e-01 6.25860150e-01 2.70697057e-01
  3.43508760e-01 2.75959731e-01 3.04555512e-02 7.23226900e-01
  2.26317943e-01 3.58706887e-01]
 [3.42134122e-01 5.42759954e-01 4.13416677e-04 8.85760698e-01
  4.69493846e-01 8.50696925e-01 7.94441081e-01 8.12708102e-01
  2.06463607e-01 3.52472023e-01]
 [4.37670282e-01 3.15507881e-03 7.18159410e-01 6.93530193e-01
  5.85813529e-02 2.92894712e-01 5.60265626e-01 5.18024111e-01
  3.08314204e-01 7.73666749e-01]
 [6.45461204e-01 6.99718356e-01 6.93035494e-01 7.92549178e

Create a random vector of size 30 and find the mean value

In [26]:
b = np.random.random(30)
print(b)
print()
print("Mean",b.mean())

[0.31047844 0.20399287 0.57216548 0.19330411 0.28564071 0.26540972
 0.54910747 0.39160636 0.4165427  0.71121063 0.32549852 0.30238773
 0.29312849 0.2533672  0.65219148 0.02290481 0.14945762 0.18598389
 0.33970478 0.99783965 0.13140459 0.11838395 0.77280315 0.56785526
 0.00118844 0.03367874 0.98238626 0.64460433 0.0218797  0.76242076]

Mean 0.3819509283789542


14. Create a 2d array with 1 on the border and 0 inside

In [37]:
x = np.ones((10,10))
print(x)
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [46]:
# #0 * np.nan
# #np.nan == np.nan
# np.inf > np.nan
# np.nan - np.nan
# 0.3 == 3 * 0.1
np.inf*2

inf

16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [59]:
x = np.diag(1+np.arange(4),k=-1)
print(x)
# y = np.diag(x,k=-1)
# print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


17. Create a 8x8 matrix and fill it with a checkerboard pattern

In [65]:
a = np.zeros((8,8), dtype = int)
#print(a)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Create a 5x5 matrix with row values ranging from 0 to 4

In [16]:
a = np.zeros(25).reshape(5,5)
print(a)
a += np.arange(5)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


Create a random vector of size 10 and sort it 

In [21]:
a = np.random.random(10)
print("Original: ",a)
b=np.sort(a)
print("Sorted: ", b)

Original:  [0.98910826 0.77265473 0.76408294 0.91531686 0.30413519 0.79581228
 0.79676814 0.28443514 0.97596308 0.93609632]
Sorted:  [0.28443514 0.30413519 0.76408294 0.77265473 0.79581228 0.79676814
 0.91531686 0.93609632 0.97596308 0.98910826]


Consider two random array A and B, check if they are equal

In [27]:
a = np.random.randint(0,2,6)
print("Array A: ",a)
b = np.random.randint(0,2,6)
print("Array B: ",b)
c = np.allclose(a,b) #compare whole array
d = np.isclose(a,b)  #compare each value
print("Are Equal: ",c)
print(d)

Array A:  [1 1 0 0 0 0]
Array B:  [0 0 0 0 1 1]
Are Equal:  False
[False False  True  True False False]
